version: '3.4'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: MarcasAut
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: 123456A*
    volumes:
      - postgres_data:/var/lib/postgresql/data

  marcasaut:
    image: ${DOCKER_REGISTRY-}marcasaut
    build:
      context: .
      dockerfile: MarcasAut/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: "Host=postgres;Port=5432;Database=MarcasAut;Username=Admin;Password=123456A*"


volumes:
  postgres_data:
